<?php 
	include('inc.php');
	$total=0;
	$samplestart='<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
	  http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!-- generated by self hosted script -->

<url>
  <loc>'.$urlhead.'</loc>
</url>';
	$sampleend='
</urlset>';
$sindex='<?xml version="1.0" encoding="UTF-8"?>
   <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
   //for playlists
	$apath="a/";
	$c=1;$t=1;
	$data=$samplestart;
	$result=$conn->query('select pid from playlists');
	while ($row = $result->fetch_assoc()) {
  $list[] = $row['pid'];
}
$total+= count($list);
	foreach($list as $link){
		$data.='
<url>
  <loc>'.$urlhead.'playlist/'.$link.'</loc>
</url>';
		$c++;
		if($c==300)
		{
			$data.=$sampleend;
			$fp = fopen('maps/playlist'.$t.'.xml', 'w');
			fwrite($fp, $data);
			fclose($fp);
			$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/playlist'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
			$t++;
			$c=1;
			$data=$samplestart;
		}
	}
	$data.=$sampleend;
	$fp = fopen('maps/playlist'.$t.'.xml', 'w');
	fwrite($fp, $data);
	fclose($fp);
	$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/playlist'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
  
	//for albums
	$apath="a/";
	$c=1;$t=1;
	$data=$samplestart;
	$result=$conn->query('select aid from albums');
	while ($row = $result->fetch_assoc()) {
  $list[] = $row['aid'];
}
$total+= count($list);
	foreach($list as $link){
		$data.='
<url>
  <loc>'.$urlhead.'album/'.$link.'</loc>
</url>';
		$c++;
		if($c==300)
		{
			$data.=$sampleend;
			$fp = fopen('maps/album'.$t.'.xml', 'w');
			fwrite($fp, $data);
			fclose($fp);
			$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/album'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
			$t++;
			$c=1;
			$data=$samplestart;
		}
	}
	$data.=$sampleend;
	$fp = fopen('maps/album'.$t.'.xml', 'w');
	fwrite($fp, $data);
	fclose($fp);
	$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/album'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
	//for songs
	$apath="s/";
	$c=1;$t=1;
	$list=array();
	$data=$samplestart;
	$result=$conn->query('select sid from songs');
	while ($row = $result->fetch_assoc()) {
  $list[] = $row['sid'];
}
$total+= count($list);
	foreach($list as $link)
	{
		$data.='
<url>
  <loc>'.$urlhead.'song/'.$link.'</loc>
</url>';
		$c++;
		if($c==300)
		{
			$data.=$sampleend;
			$fp = fopen('maps/song'.$t.'.xml', 'w');
			fwrite($fp, $data);
			fclose($fp);
	$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/song'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
			$t++;
			$c=1;
			$data=$samplestart;
		}
	}
	$data.=$sampleend;
	$fp = fopen('maps/song'.$t.'.xml', 'w');
	fwrite($fp, $data);
	fclose($fp);
	$sindex.='
  <sitemap>
    <loc>'.$urlhead.'maps/song'.$t.'.xml</loc>
    <lastmod>'.date('Y-m-d\TH:i:sP').'</lastmod>
  </sitemap>';
	$sindex.='
  </sitemapindex>';
$fp = fopen('sitemap.xml', 'w');
fwrite($fp, $sindex);
fclose($fp);
	echo $total.' sitemaps generated';
?>